"""Positive Fourier multipliers generated by prime shifts."""

from __future__ import annotations

import math


def prime_shift_multiplier(xi: float, prime_powers: list[tuple[int, int]], coefficients: list[float], epsilon: float = 0.0) -> float:
    """Evaluate q(xi)=eps+sum c|1-exp(i xi r log p)|^2."""
    if len(prime_powers) != len(coefficients):
        raise ValueError("prime_powers and coefficients must have equal length")
    if epsilon < 0 or any(c < 0 for c in coefficients):
        raise ValueError("positivity requires epsilon and coefficients >= 0")
    return epsilon + sum(c * 2 * (1 - math.cos(xi * r * math.log(p))) for (p, r), c in zip(prime_powers, coefficients))


def multiplier_status(coefficients: list[float], epsilon: float = 0.0) -> dict[str, object]:
    return {
        "positive_by_construction": epsilon >= 0 and all(c >= 0 for c in coefficients),
        "strictly_positive": epsilon > 0,
        "commutes_with_D": True,
        "status": "PATTERN_ONLY",
    }
